# Generated by Django 3.1.5 on 2021-02-08 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkts', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='berth_date',
            field=models.DateField(default=datetime.date(2021, 2, 8)),
        ),
    ]
