# Generated by Django 3.1.5 on 2021-02-15 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkts', '0007_auto_20210208_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('PHONE', 'PHONE'), ('CAR', 'CAR'), ('PC', 'PC')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='berth_date',
            field=models.DateField(default=datetime.date(2021, 2, 15)),
        ),
    ]
